### ISSUE TITLE
怎么把BIWI和AFLW数据集转换为此项目中训练代码可以调用的格式？

### ISSUE THREAD

**Issue by LD421083** [haofanwang/accurate-head-pose#11]
我在尝试使用BIWI和AFLW数据集按照此提出的代码进行训练时，需要提取bbox文件，但是下载的数据集没有，想请问是怎么把它转换为类似300W_LP或者AFLW2000数据集那样可以直接采用此代码调用。盼回复，谢谢。

**Comment by haofanwang** [comment]
请参考[deep-head-pose](https://github.com/natanielruiz/deep-head-pose)，我只在dataloader中做了部分修改，数据预处理与这份代码完全相同。

**Comment by wqz960** [comment]
@LD421083 hi！您可以提供我下载BIWI和AFLW数据集的下载地址吗？谢谢您！

**Comment by jt19520** [comment]
@LD421083 hi,您好，请问您现在解决了这个问题吗？请问您是否能提供一下bounding box文件

**Comment by LD421083** [comment]
> @LD421083 hi！您可以提供我下载BIWI和AFLW数据集的下载地址吗？谢谢您！
AFLW
链接: https://pan.baidu.com/s/1XbkUIqRvUExewaSpjBbJXw  密码: s2l7
BIWI
链接: https://pan.baidu.com/s/13hjoSj4SoYCo-l_3rbd6Bw  密码: 22q5

**Comment by LD421083** [comment]
> @LD421083 hi,您好，请问您现在解决了这个问题吗？请问您是否能提供一下bounding box文件

暂时没有解决。

**Comment by LD421083** [comment]
> 请参考[deep-head-pose](https://github.com/natanielruiz/deep-head-pose)，我只在dataloader中做了部分修改，数据预处理与这份代码完全相同。

好的，谢谢你回复。

**Comment by wqz960** [comment]
@jt19520 @LD421083  可以参考FSANet的BIWI生成方式，里面用了MTCNN做人脸检测，或者https://github.com/wqz960/facial_landmark_label-，里面提高了BIWI每张人脸的68点关键点，取最大最小值就是boundingbox。

**Comment by jt19520** [comment]
> @jt19520 @LD421083 可以参考FSANet的BIWI生成方式，里面用了MTCNN做人脸检测，或者[https://github.com/wqz960/facial_landmark_label-，里面提高了BIWI每张人脸的68点关键点，取最大最小值就是boundingbox。](https://github.com/wqz960/facial_landmark_label-%EF%BC%8C%E9%87%8C%E9%9D%A2%E6%8F%90%E9%AB%98%E4%BA%86BIWI%E6%AF%8F%E5%BC%A0%E4%BA%BA%E8%84%B8%E7%9A%8468%E7%82%B9%E5%85%B3%E9%94%AE%E7%82%B9%EF%BC%8C%E5%8F%96%E6%9C%80%E5%A4%A7%E6%9C%80%E5%B0%8F%E5%80%BC%E5%B0%B1%E6%98%AFboundingbox%E3%80%82)

感谢您的回复。我试过了，但是使用FSANet的Bounding box文件并不与原作者的格式完全匹配，从而误差比较大，是不是还有什么细节我没注意到呢？

**Comment by wqz960** [comment]
@jt19520 你的精度大概是多少，最好用face landmark 来做boundingbox，我试了一下 误差biwi的也快5了。

**Comment by nickname-wang** [comment]
> @jt19520 你的精度大概是多少，最好用face landmark 来做boundingbox，我试了一下 误差biwi的也快5了。

你好，请问你的学习率，batch size， eopch 如何设置的呢，我使用facial landmark做bbox，但是误差接近10，是有什么地方需要修改吗？
