### ISSUE TITLE
权重参数7 5 3 11 依据是什么

### ISSUE THREAD

**Issue by shiyuanyin** [haofanwang/accurate-head-pose#2]
@haofanwang ，您好，作者，我读了您的论文，我想问下，对于设置权重参数7 5 3 11 依据是什么，是你做实验实验出来的吗？
我的理解是，反向传播中，回归的损失值，和 分类损失值是设置1：1 的大致比例，然后进行实验的微调吗？

**Comment by haofanwang** [comment]
You're right, It's just a setting based on several experiments. Specific parameter setting is not our focus of concern, multi classification branch is the key here.

**Comment by shiyuanyin** [comment]
@haofanwang   虽然，您在论文上说，粗分类和细分类结合训练效果更好，但是我仍然不知道，您这么设计的根本原因是什么？是什么启发了你，想到这种方式？

**Comment by haofanwang** [comment]
本质上可以理解成一种对问题的relax。

在实际的应用场景（例如DMS报警系统）中，我们发现，单分类分支+回归方法（依赖于关键点的方法也会存在这种问题）偶尔会存在比较严重的错误预测（尤其是正负符号的错误预测，左转头被预测为右转头），这是不能容忍的。所有我们的出发点是提高模型预测的稳定性，减少这种明显可以避免的错误。所以我们起初额外引入了一个二分类分支来解决符号的错误预测问题，真实环境中测试表明明显错误的情况会有所减少，所以我们会想，再增加几个不同尺寸的分支会不会也会有帮助呢，在不同尺度都要求网络能够准确分类最终会不会提高网络的稳定性呢。我们也尝试过在不同epoch阶段使用不同精度的分类、多分支结果的融合处理。

**Comment by shiyuanyin** [comment]
@haofanwang 特别感谢您能够抽时间回复。

**Comment by haofanwang** [comment]
Closed. If it's helpful to you, please star our project. @shiyuanyin
