### ISSUE TITLE
model idea

### ISSUE THREAD

**Issue by iperov** [haofanwang/accurate-head-pose#3]
i am trying my idea to predict pitch,yaw,roll

input: aligned face, mask of it from 68 points

model1: encoder -> latent(512) -> decoder
model2: latent(512) -> dense... -> pitch,yaw,roll (hybrid coarse-fine)

model1 train:
```
rec = model1( [randomly warped and transformed inp_face] )

DSSIM ( transformed inp_face*inp_mask, rec*inp_mask )
```

model2 train:
```
latent space of model1(inp_face) -> pitch,yaw,roll (hybrid coarse-fine)
```

mask excludes background
DSSIM faster reconstruct an image by pushing attention to edges first
model2 training to fetch pitch,yaw,roll info from latent of decoder space

it seems it works

![python_2019-04-24_20-14-30](https://user-images.githubusercontent.com/8076202/56675587-91165700-66cd-11e9-817c-6140ec4ad504.jpg)

model2 config
```
x = latent

            x = Dense(4096, activation='relu')(latent)

            output = []
            for class_num in class_nums:
                pitch = Dense(class_num, activation='softmax')(x)
                yaw = Dense(class_num, activation='softmax')(x)
                roll = Dense(class_num, activation='softmax')(x)
                output += [pitch,yaw,roll]
                
            return output
```
any advice? should I add more dense and/or dropout?

**Comment by haofanwang** [comment]
Sorry, I don't get your point, may you state it more clearly?

**Comment by iperov** [comment]
new idea. Now works better!

First we train BVAE on celeba faces, so latent space become regulazired by network.

![dldisentangling-by-factorising-14-638 1](https://user-images.githubusercontent.com/8076202/56949653-86801580-6b44-11e9-9f2b-e0cdf7149809.jpg)

Second train simple pose predictor from latent space with L2 loss.

![python_2019-04-30_12-33-49](https://user-images.githubusercontent.com/8076202/56949515-3012d700-6b44-11e9-834e-78c9cab820d1.jpg)

**Comment by haofanwang** [comment]
That sounds great. Closed.
