### ISSUE TITLE
The data set seems to need processing

### ISSUE THREAD

**Issue by ZhongyuMa** [haofanwang/accurate-head-pose#6]
How do you process the BIWI data set？

**Comment by ZhongyuMa** [comment]
File "train_hopenet.py", line 165, in <module>
    for i, (images, labels, labels_0, labels_1, labels_2, labels_3, cont_labels, name) in enumerate(train_loader):
ValueError: not enough values to unpack (expected 8, got 4)

**Comment by haofanwang** [comment]
Hi @ZhongyuMa, thanks for following our work. if you want to process the BIWI dataset, be sure to you set the arg as below.

`parser.add_argument('--dataset', dest='dataset', help='Dataset type.', default='BIWI_multi', type=str)`

Please let me know if you have any other questions.

**Comment by haofanwang** [comment]
Closed.
