### ISSUE TITLE
Pretrained models on require Baidu network disk client.

### ISSUE THREAD

**Issue by SteveCohen** [haofanwang/accurate-head-pose#9]
Is it possible to store your pretrained models on a hosting service different to Baidu? Baidu require a network disk client to download them, which I do not have and cannot install.

**Comment by haofanwang** [comment]
@SteveCohen Thanks for your interest.

I will upload the pretrained models on Google Drive soon.

**Comment by haofanwang** [comment]
Hi, @SteveCohen , I have uploaded all pretrained models into Google Drive. 

[pretrained](https://drive.google.com/drive/folders/1is55mbFHsAVbeStkIZf9LV4HdiSjJHd9?usp=sharing)
